version: '3.8'

services:
  magaz:
    build: .
    ports:
      - "7777:80"
    volumes:
      - ./service:/var/www/html
    depends_on:
      - mysql
    networks:
      - internal_network
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mysql_db
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - internal_network
    restart: always

networks:
  internal_network:
    driver: bridge
